### PR TITLE
:bug: Multiple minor fixes

### LINKED ISSUE #833: 🐛 Latest meeting is loading forever if it's "missing"
If the latest meeting is missing, optimally we should search for a meeting the previous year.

image

### LINKED ISSUE #860: ✨ Add option to see history of bookings
## Short description of the feature
It should be possible to see who has made bookings before, maybe only for Head of Facilities since they are responsible for the locals and inventory. They also oversee the bookings in the first place. It would be good to save *at least* the last 5 bookings for every bookable item. 

## Why do you want this feature?
If something is wrong after a booking it would be good to know who last had/used it. Having at least the last 5 bookings is for in case a frequently used item breaks, and there have been a couple bookings since it could be used properly. I want to be able to keep track of who to talk to about what happened, in case no one tells me directly that something broke.  

## Who else could want this feature?
... Future Head of Facilities? :)

### LINKED ISSUE #896: ✨ Make board meeting documents the default
## Short description of the feature
In the meeting documents page, the documents are filtered by year and type. The board meeting documents should be the default filter for the meeting-type. 

## Why do you want this feature?
Board meetings (styrelsemöten) are a weekly occurance and the documents are visited each week while the general assembly meetings (sektionsmöten) are held only a few times per year.  I want to more easily be able to access the documents that are relevant each week (rather than a few times per year).

## Who else could want this feature?
All members that wish to keep up with the daily operations of the guild, as well as all the board members and regular attendees of the board meetings.

### LINKED ISSUE #918: ✨ Pressing the text that tells me how many comments an article has should take me to the comments
## Short description of the feature

Pressing `1 comment` should open the article and show comments.

https://user-images.githubusercontent.com/71255627/219660329-df1e35ef-1768-4f5f-add4-e3c7196f4bc2.mov

## Why do you want this feature?
It's kinda standard, the text is even already highlighted when hovering over it.

## Who else could want this feature?
Peeps in general <3

### PR DESCRIPTION
**Pull request by Macludde**
Closes #896
Closes #918 
Closes #833 
Closes #860 ? (depends on what the issue actually meant, but you CAN see bookings from the past now)

A whole lot of smaller fixes which would just take a lot of time to split up into multiple PRs.

### CODE REVIEW

File: backend/services/core/src/datasources/Mandate.ts
Comment (danieladugyan) [inline backend/services/core/src/datasources/Mandate.ts:1]: Not necessary to add this in this MR, but do we have translation support for these messages? i.e `message_en`, `title_en`

File: frontend/components/Documents/index.tsx [hunk 1]
```diff
@@ -17,18 +17,14 @@ type Filter = {
...
-    filter: (meetings: Meeting[]) => meetings.filter((meeting) => meeting.title.toUpperCase().includes('VTM')),
-  },
   {
     title: 'Styrelsemöten',
     filter: (meetings: Meeting[]) => meetings.filter((meeting) => meeting.title.toUpperCase().match(/(S\d{2})/)),
   },
+  {
+    title: 'Sektionsmöten',
+    filter: (meetings: Meeting[]) => meetings.filter((meeting) => meeting.title.toUpperCase().includes('HTM') || meeting.title.toUpperCase().includes('VTM')),
+  },
```
Comment (danieladugyan) [inline frontend/components/Documents/index.tsx:27]: Do we want to group these? Maybe we do - I personally don't really have any strong preference either way.

File: frontend/components/Header/index.tsx [hunk 2]
```diff
@@ -57,7 +57,7 @@ function Header() {
       spacing={{ xs: 1, md: 2 }}
       sx={{
         position: 'fixed',
-        zIndex: 2,
+        zIndex: 100,
```
Comment (danieladugyan) [inline frontend/components/Header/index.tsx:60]: In general I feel like we might be overusing zIndex? Not looking at this one in particular, but overall we've ran into a few issues stemming from excessive zIndex-ing.

File: frontend/components/Home/DisplayMeeting.tsx [hunk 3]
```diff
@@ -6,13 +6,14 @@ import processFilesData from '../Documents/proccessFilesData';
...
-  const { data } = useFilesQuery({ variables: { bucket: 'documents', prefix: `public/${thisYear}`, recursive: true } });
+  const { data, loading } = useFilesQuery({ variables: { bucket: 'documents', prefix: `public/${thisYear}`, recursive: true } });
   const meetings = processFilesData(thisYear, data?.files || [])
     .filter((m) => m.modDate).sort((a, b) => (a.modDate < b.modDate ? 1 : -1));
   // sort meetings after date
 
   const latestMeeting = meetings[index];
-  if (!latestMeeting) return <CircularProgress />;
+  if (loading) return <CircularProgress />;
+  if (!latestMeeting) return null;
```
Comment (danieladugyan) [inline frontend/components/Home/DisplayMeeting.tsx:16]: Finally! This annoyed me so much 😄

File: frontend/providers/UserProvider.tsx [hunk 4]
```diff
@@ -56,7 +56,10 @@ export function UserProvider({ children }: PropsWithChildren<{}>) {
         setShouldReroute(true);
       }
     }
-  }, [data?.me, status, loading]);
+  // I'm not quite sure why this is the way it is, but it seems like "shouldReroute"
+  // is used to force this to have to be called twice before re-routing
+  // Obviously, including it disables that functionality
+  }, [data?.me, status, loading]); // eslint-disable-line react-hooks/exhaustive-deps
```
Comment (danieladugyan) [inline frontend/providers/UserProvider.tsx:62]: This odd behaviour is fixed by #1002.

**Review by danieladugyan — APPROVED** [review]
Much needed fixes, great! I had some comments/questions, but no required changes imo.

File: backend/services/core/src/datasources/Mandate.ts
Comment (Macludde) [reply backend/services/core/src/datasources/Mandate.ts:1]: Nope, because preferred language handling for notifications is difficult :(

File: frontend/components/Documents/index.tsx (hunk 1 above)
Comment (Macludde) [reply frontend/components/Documents/index.tsx:27]: I think so, and the people from at least the board agreed. I see no reason to split them up.

File: frontend/components/Header/index.tsx (hunk 2 above)
Comment (Macludde) [reply frontend/components/Header/index.tsx:60]: The point was to be the highest on the entire site, no matter what other components are doing. This allows devs to be a little excessive with zIndex when developing components, without having to worry about screwing up menu and header overlap.

File: frontend/components/Home/DisplayMeeting.tsx (hunk 3 above)
Comment (Macludde) [reply frontend/components/Home/DisplayMeeting.tsx:16]: ☺️

File: frontend/providers/UserProvider.tsx (hunk 4 above)
Comment (Macludde) [reply frontend/providers/UserProvider.tsx:62]: Nice!

**Comment by Macludde** [comment]
Before merging, does this close #860?
