### PR TITLE
:bug: Make sure that pdf API version and worker version are synced

### LINKED ISSUE #1174: 🐛 Governing Documents not working as intended
## Short description of the bug
The buttons for statutes and regulations do not work properly, nor do the policies and guidelines show.

## To Reproduce
Go to "Documents" -> "Governing Documents"

## Expected behavior
The pink buttons should redirect to the correct page of each document. Also, the policies and guidelines should be shown in a similar way to how our meeting documents are visible.

## Actual behavior
The larger, pink buttons do not redirect to the documents as they should with the error message in the picture below. Also, the policies and guidelines are not visible.

## Context
image

### LINKED ISSUE #1237: 🐛 Previews for the guild statues and regulations are broken
When I click the button for the preview of the statues document, an error message shows up:

image

### PR DESCRIPTION
**Pull request by oliverlevay**
Closes #1237 
Closes #1174

### CODE REVIEW

File: frontend/components/GoverningDocuments/DocumentButton.tsx [hunk 1]
```diff
@@ -14,6 +14,7 @@ import { useDeleteGoverningDocumentMutation } from '~/generated/graphql';
 import { useApiAccess } from '~/providers/ApiAccessProvider';
 import Link from '../Link';
 import routes from '~/routes';
+import packageJson from '../../package.json';
```
Comment (danieladugyan) [inline frontend/components/GoverningDocuments/DocumentButton.tsx:17]: That's a neat solution, but I would suggest using package-lock.json instead to ensure it's the right version.

**Review by danieladugyan — CHANGES_REQUESTED** [review]
