### PR TITLE
💄 1022 the entire site should look better on desktop

### LINKED ISSUE #775: 🐛 Limit the size of the cards in the committee pages
### Short description of the bug
The cards can get reaaaally long when there are a lot of people with mandates for a certain position.

### To Reproduce
Look at the committee page for NollU. There are like 100 nollningsfunktionärer.

### Expected behavior
Pagination or truncation of the people holding the position so that the card is shorter.

### Actual behavior
A really long card.

### LINKED ISSUE #1022: The entire page should look better on desktop by using a container

### PR DESCRIPTION
**Pull request by Macludde**
Closes #1022 
Closes #775 

The main part of this PR WAS to add a container wrapping the entire site. When going through all the pages I noticed multiple of them were quite lacking in their design on many pages, and I then updated the relevant pages on by one.

So a (perhaps incomplete) list of all the updates that this PR does is:
- Add wrapping container to entire page and header
- Re-design position pages to use the X-axis more
- Re-design commitees pages a little (to use X-axis more)
- Add expandable table to bookings page
- Fix header overflow on smaller screens
- Change calendar to use month by default
- Re-design meeting documents page to use X-axis
- Show preview of contents on news article card in list, same forevents
- Re-design article card style to be more horizontal
- Re-design event cards to be more horizontal
- Add contact us to app landing page
- Add reply ability on comments

### CODE REVIEW

**Comment by danieladugyan** [comment]
Issue with calendar overflowing
image

**Comment by danieladugyan** [comment]
Issue with navbar overflowing when authentication is loading
image

File: frontend/components/Committees/CommitteesList.tsx [hunk 1]
```diff
@@ -8,23 +8,16 @@ import useCommittees from '~/hooks/useCommittees';
 import routes from '~/routes';
 import CommitteeIcon from './CommitteeIcon';
 
-const Card = styled(Stack)(({ theme }) => `
```
Comment (danieladugyan) [inline frontend/components/Committees/CommitteesList.tsx:11]: How come we use styled instead of sx-prop?

File: frontend/components/Documents/Meeting.tsx [hunk 2]
```diff
@@ -10,37 +11,53 @@ const MeetingPaper = styled(Paper)`
...
+        display: 'grid',
+        gridTemplateColumns: 'repeat(auto-fill, minmax(250px, 1fr))',
+        gap: 2,
+      }}
+      >
+        {meeting.files.map((file) => {
+          const title = file.name.replaceAll('_', ' ');
+
+          return (
+            <Tooltip
```
Comment (danieladugyan) [inline frontend/components/Documents/Meeting.tsx:31]: Tooltip doesn't fill much of a purpose?
image

**Comment by danieladugyan** [comment]
This dropdown should probably appear to the left instead ("inside" the container)
image

**Comment by danieladugyan** [comment]
@Macludde Some minor bugs/questions, but other than that it's a massive improvement. Nice work!

File: frontend/components/Documents/Meeting.tsx (hunk 2 above)
Comment (Macludde) [reply frontend/components/Documents/Meeting.tsx:31]: For files with long file names they will be truncated (with ellipsis "..."). So the tooltip is there to see the full name.
